defaults:
  - _self_

data_path: /home/data/huggingface
runs_path: /home/data/speeder

team_name: null # optional wandb team name
project_name: speeder-test # required wandb project name

user: ${oc.env:USER,unnamed}

hydra:
  run:
    dir: .
  output_subdir: null
