defaults:
  - _self_

data_path: /data/huggingface
runs_path: /data/speeder

team_name: bigml_sam # optional wandb team name
project_name: parallel-test-3 # required wandb project name

user: ${oc.env:USER,unnamed}

overrides: null

hydra:
  run:
    dir: .
  output_subdir: null
