defaults:
  - global_cfg@_here_
  - _self_

# RAY PARAMS

global_batch_size: 1024
prefetch_batches: 2

num_data_workers: 4
cpus_per_data_worker: 1
gpus_per_data_worker: 0

num_train_workers: 8
cpus_per_train_worker: 2
gpus_per_train_worker: 1

use_gpu: True

# TRAINING PARAMS

epochs: 10
lr: 0.001