defaults:
  - global_cfg@_here_
  - _self_

# CONFIG PARAMS

exp_name: null # required
run_name: null # required

debug: false

# RAY PARAMS

prefetch_batches: 1

data_workers: 1
cpus_per_data_worker: 1
gpus_per_data_worker: 0

train_workers: 1
cpus_per_train_worker: 1
gpus_per_train_worker: 1

gpu_ids: -1

# MODEL PARAMS

# DATA PARAMS

batch_size: 1024

# TRAINING PARAMS

# Pass either a ray tune entry or just pass the parameter as normal
# List of supported entries: https://docs.ray.io/en/latest/tune/api/search_space.html

num_trials: 1 # Actual number of trials is num_trials * len(grid_search_params)

epochs: 10
lr: 0.01
pr: 0.1
